rule Metasploit {
  meta:
    author = "Dylan Meca"
    description = "Detection of .exe or .apk files generated by metasploit"
  strings:
    $a = /PAYLOAD:[\w\d\-\_]+/
    $b = /AndroidManifest\.xml/
    $c = /classes\.dex/
    $d = /META-INF\/PK/
    $e = /META-INF\/MANIFEST\.MF\]/
    $f = /META-INF\/SIGNFILE\.SF\]/
    $g = /META-INF\/SIGNFILE\.RSA[\w\d]+/
    $h = /META-INF\/MANIFEST\.MFPK/
    $i = /META-INF\/SIGNFILE\.SFPK/
    $j = /META-INF\/SIGNFILE\.RSAPK/
    $k = /\$cT\[[\w\d\-\_]+\]/
    $l = /5CCP/
    $m = /\/hd\//
    $n = /\^\WTY/
    $o = /\(_E;D/
    
  condition:
    any of ($a, $b, $c, $d, $e, $f, $g, $h, $i, $j, $k, $l, $m, $n, $o)
  }
  
rule JavaDropper
{
    meta:
	    author = " Kevin Breen <kevin@techanarchy.net>"
	    date = "2015/10"
	    ref = "http://malwareconfig.com/stats/AlienSpy"
	    maltype = "Remote Access Trojan"
	    filetype = "exe"

    strings:
	    $jar = "META-INF/MANIFEST.MF"

	    $a1 = "ePK"
	    $a2 = "kPK"

        $b1 = "config.ini"
        $b2 = "password.ini"

        $c1 = "stub/stub.dll"

        $d1 = "c.dat"

    condition:
        $jar and (all of ($a*) or all of ($b*) or all of ($c*) or all of ($d*))
}

rule Meterpreter_Reverse_Tcp { 
  meta: // This is the standard backdoor/RAT from Metasploit, could be used by any actor 
    author = "chort (@chort0)" 
    description = "Meterpreter reverse TCP backdoor in memory. Tested on Win7x64." 
  strings: 
    $a = { 4d 45 54 45 52 50 52 45 54 45 52 5f 54 52 41 4e 53 50 4f 52 54 5f 53 53 4c [32-48] 68 74 74 70 73 3a 2f 2f 58 58 58 58 58 58 } // METERPRETER_TRANSPORT_SSL … https://XXXXXX 
    $b = { 4d 45 54 45 52 50 52 45 54 45 52 5f 55 41 } // METERPRETER_UA 
    $c = { 47 45 54 20 2f 31 32 33 34 35 36 37 38 39 20 48 54 54 50 2f 31 2e 30 } // GET /123456789 HTTP/1.0 
    $d = { 6d 65 74 73 72 76 2e 64 6c 6c [2-4] 52 65 66 6c 65 63 74 69 76 65 4c 6f 61 64 65 72 } // metsrv.dll … ReflectiveLoader 
    
  condition: 
    $a or (any of ($b, $d) and $c) 
  }
