rule Metasploit {
  meta:
    author = "Dylan Meca"
    description = "Detection of .exe files generated by metasploit"
  strings:
    $a = "PAYLOAD:"
    
  condition:
    $a
  }
  
rule JavaDropper
{
    meta:
	    author = " Kevin Breen <kevin@techanarchy.net>"
	    date = "2015/10"
	    ref = "http://malwareconfig.com/stats/AlienSpy"
	    maltype = "Remote Access Trojan"
	    filetype = "exe"

    strings:
	    $jar = "META-INF/MANIFEST.MF"

	    $a1 = "ePK"
	    $a2 = "kPK"

        $b1 = "config.ini"
        $b2 = "password.ini"

        $c1 = "stub/stub.dll"

        $d1 = "c.dat"

    condition:
        $jar and (all of ($a*) or all of ($b*) or all of ($c*) or all of ($d*))
}

rule autogen_peexe_ObfuscatedGreywareOverlayPackedShell32dll_5ab5f39d
{
	meta:
		author = "FileScan.IO Engine v1.1.0-c6ec042"
		date = "2022-12-25"
		sample = "5ab5f39d143b6ff77df2fd5026ac8e4788edfd3de27a4e1fa4b420a7d2f61d38"
		score = 20
		tags = "obfuscated,greyware,overlay,packed,shell32.dll"
		isWeakRule = false

	strings:

		//IOC patterns
		$req0 = "!http://crl.trustwave.com/STCA.crl0="
		$req1 = "\"http://crl.trustwave.com/TWGCA.crl0n"
		$req2 = "$Lua: Lua 5.1.4 Copyright (C) 1994-2008 Lua.org, PUC-Rio $\n$Authors: R. Ierusalimschy, L. H. de Figueiredo & W. Celes $\n$URL: ww"
		$req3 = "%http://crl.trustwave.com/CSCA2_L1.crl0q"
		$req4 = ")http://crl.securetrust.com/TWGTSCA_L1.crl0y"
		$req5 = ")http://ssl.trustwave.com/issuers/STCA.crt0"
		$req6 = "*http://ssl.trustwave.com/issuers/TWGCA.crt0"
		$req7 = "-http://ssl.trustwave.com/issuers/CSCA2_L1.crt0"
		$req8 = "/http://crt.comodoca.com/COMODORSAAddTrustCA.crt0$"
		$req9 = "1994-2015 Lua.org, PUC-Rio."
		$req10 = "1http://crl.usertrust.com/UTN-USERFirst-Object.crl05"
		$req11 = "2019 Indigo Rose Corporation (www.indigorose.com)"
		$req12 = "2http://crl.comodoca.com/COMODORSACodeSigningCA.crl0t"
		$req13 = "2http://crt.comodoca.com/COMODORSACodeSigningCA.crt0$"
		$req14 = "3http://certs.securetrust.com/issuers/TWGTSCA_L1.crt0"
		$req15 = ";http://crl.comodoca.com/COMODORSACertificationAuthority.crl0q"
		$req16 = "<?xml version=\"1.0\" encoding=\"UTF-8\" standalone=\"yes\"?> \r\n<assembly xmlns=\"urn:schemas-microsoft-com:asm.v1\" manifestVersion=\"1."
		$req17 = "<supportedOS Id=\"{35138b9a-5d96-4fbd-8e2d-a2440225f93a}\"/>\r\n\t\t\t<!-- Windows 8 Support -->\r\n\t\t\t\t<supportedOS Id=\"{4a2f28e3-53b9-4"
		$req18 = "ca@trustwave.com"
		$req19 = "http://ocsp.securetrust.com/0?"
		$req20 = "http://ocsp.trustwave.com/06"
		$req21 = "http://ocsp.trustwave.com/09"
		$req22 = "http://www.indigorose.com 0"
		$req23 = "https://certs.securetrust.com/CA0:"
		$req24 = "https://secure.comodo.net/CPS0C"
		$req25 = "https://ssl.trustwave.com/CA03"
		$req26 = "https://ssl.trustwave.com/CA06"
		$req27 = "https://ssl.trustwave.com/CA0l"
		$req28 = "www.lua.org"

		//optional strings
		$opt0 = "ADVAPI32.dll"
		$opt1 = "Advapi32.dll"
		$opt2 = "COMCTL32.dll"
		$opt3 = "COMDLG32.dll"
		$opt4 = "ConvertSidToStringSidA"
		$opt5 = "CreateDirectoryA"
		$opt6 = "CreateFileA"
		$opt7 = "CreatePipe"
		$opt8 = "CreateProcessA"
		$opt9 = "DecodePointer"
		$opt10 = "DeleteCriticalSection"
		$opt11 = "DeleteFileA"
		$opt12 = "DispatchMessageA"
		$opt13 = "DuplicateHandle"
		$opt14 = "EncodePointer"
		$opt15 = "EnterCriticalSection"
		$opt16 = "EnumSystemLocalesA"
		$opt17 = "ExitProcess"
		$opt18 = "FlushFileBuffers"
		$opt19 = "FormatMessageA"
		$opt20 = "FreeEnvironmentStringsA"
		$opt21 = "FreeEnvironmentStringsW"
		$opt22 = "FreeLibrary"
		$opt23 = "GetActiveWindow"
		$opt24 = "GetCommandLineA"
		$opt25 = "GetConsoleCP"
		$opt26 = "GetConsoleMode"
		$opt27 = "GetConsoleOutputCP"
		$opt28 = "GetCurrentDirectoryA"
		$opt29 = "GetCurrentProcess"
		$opt30 = "GetCurrentProcessId"
		$opt31 = "GetCurrentThreadId"
		$opt32 = "GetDateFormatA"
		$opt33 = "GetDiskFreeSpaceA"
		$opt34 = "GetEnvironmentStrings"
		$opt35 = "GetEnvironmentStringsW"
		$opt36 = "GetExitCodeProcess"
		$opt37 = "GetFileAttributesA"
		$opt38 = "GetFileType"
		$opt39 = "GetLastActivePopup"
		$opt40 = "GetLastError"
		$opt41 = "GetLocaleInfoA"
		$opt42 = "GetLocaleInfoW"
		$opt43 = "GetModuleFileNameA"
		$opt44 = "GetModuleFileNameW"
		$opt45 = "GetModuleHandleA"
		$opt46 = "GetModuleHandleW"
		$opt47 = "GetProcAddress"
		$opt48 = "GetProcessHeap"
		$opt49 = "GetProcessWindowStation"
		$opt50 = "GetStartupInfoA"
		$opt51 = "GetStartupInfoW"
		$opt52 = "GetStdHandle"
		$opt53 = "GetStringTypeA"
		$opt54 = "GetStringTypeW"
		$opt55 = "GetSystemDirectoryA"
		$opt56 = "GetSystemTimeAsFileTime"
		$opt57 = "GetTempPathA"
		$opt58 = "GetTickCount"
		$opt59 = "GetTimeFormatA"
		$opt60 = "GetTimeZoneInformation"
		$opt61 = "GetTokenInformation"
		$opt62 = "GetUserDefaultLCID"
		$opt63 = "GetUserObjectInformationA"
		$opt64 = "GetUserObjectInformationW"
		$opt65 = "HeapCreate"
		$opt66 = "HeapDestroy"
		$opt67 = "HeapReAlloc"
		$opt68 = "HeapSetInformation"
		$opt69 = "ImageDirectoryEntryToData"
		$opt70 = "ImmGetContext"
		$opt71 = "InitializeCriticalSectionAndSpinCount"
		$opt72 = "InterlockedDecrement"
		$opt73 = "InterlockedIncrement"
		$opt74 = "IsDebuggerPresent"
		$opt75 = "IsProcessorFeaturePresent"
		$opt76 = "KERNEL32.DLL"
		$opt77 = "KERNEL32.dll"
		$opt78 = "LCMapStringA"
		$opt79 = "LCMapStringW"
		$opt80 = "LeaveCriticalSection"
		$opt81 = "LoadCursorA"
		$opt82 = "LoadLibraryA"
		$opt83 = "LoadLibraryW"
		$opt84 = "MSIMG32.dll"
		$opt85 = "MoveFileExA"
		$opt86 = "MsgWaitForMultipleObjects"
		$opt87 = "NETAPI32.dll"
		$opt88 = "OLEACC.dll"
		$opt89 = "OLEAUT32.dll"
		$opt90 = "OpenProcessToken"
		$opt91 = "PROPSYS.dll"
		$opt92 = "PeekMessageA"
		$opt93 = "QueryPerformanceCounter"
		$opt94 = "RaiseException"
		$opt95 = "RemoveDirectoryA"
		$opt96 = "SHELL32.dll"
		$opt97 = "SHLWAPI.dll"
		$opt98 = "Secur32.dll"
		$opt99 = "SetCurrentDirectoryA"
		$opt100 = "SetDefaultDllDirectories"
		$opt101 = "SetDllDirectoryA"
		$opt102 = "SetEndOfFile"
		$opt103 = "SetEnvironmentVariableA"
		$opt104 = "SetFilePointer"
		$opt105 = "SetHandleCount"
		$opt106 = "SetLastError"
		$opt107 = "SetStdHandle"
		$opt108 = "SetUnhandledExceptionFilter"
		$opt109 = "ShellExecuteExA"
		$opt110 = "TerminateProcess"
		$opt111 = "TlsGetValue"
		$opt112 = "TlsSetValue"
		$opt113 = "TranslateMessage"
		$opt114 = "URLDownloadToFileA"
		$opt115 = "USER32.DLL"
		$opt116 = "USER32.dll"
		$opt117 = "UnhandledExceptionFilter"
		$opt118 = "VERSION.dll"
		$opt119 = "VirtualAlloc"
		$opt120 = "VirtualFree"
		$opt121 = "VirtualProtect"
		$opt122 = "WINSPOOL.DRV"
		$opt123 = "WaitForSingleObject"
		$opt124 = "WriteConsoleA"
		$opt125 = "WriteConsoleW"
		$opt126 = "control structure too long"
		$opt127 = "gdiplus.dll"
		$opt128 = "imagehlp.dll"
		$opt129 = "kernel32.dll"
		$opt130 = "loadstring"
		$opt131 = "mscoree.dll"
		$opt132 = "ntmarta.dll"
		$opt133 = "urlmon.dll"

	condition:
		//require 90% of IOC patterns and require 50% of optional strings
		uint16(0) == 0x5A4D and filesize > 20438410 and filesize < 24980278 and 26 of ($req*) and 67 of ($opt*)
}

rule Meterpreter_Reverse_Tcp { 
  meta: // This is the standard backdoor/RAT from Metasploit, could be used by any actor 
    author = "chort (@chort0)" 
    description = "Meterpreter reverse TCP backdoor in memory. Tested on Win7x64." 
  strings: 
    $a = { 4d 45 54 45 52 50 52 45 54 45 52 5f 54 52 41 4e 53 50 4f 52 54 5f 53 53 4c [32-48] 68 74 74 70 73 3a 2f 2f 58 58 58 58 58 58 } // METERPRETER_TRANSPORT_SSL … https://XXXXXX 
    $b = { 4d 45 54 45 52 50 52 45 54 45 52 5f 55 41 } // METERPRETER_UA 
    $c = { 47 45 54 20 2f 31 32 33 34 35 36 37 38 39 20 48 54 54 50 2f 31 2e 30 } // GET /123456789 HTTP/1.0 
    $d = { 6d 65 74 73 72 76 2e 64 6c 6c [2-4] 52 65 66 6c 65 63 74 69 76 65 4c 6f 61 64 65 72 } // metsrv.dll … ReflectiveLoader 
    
  condition: 
    $a or (any of ($b, $d) and $c) 
  }

rule Cobalt_functions
{

    meta:

        author="@j0sm1"
        url="https://www.securityartwork.es/2017/06/16/analisis-del-powershell-usado-fin7/"
        description="Detect functions coded with ROR edi,D; Detect CobaltStrike used by differents groups APT"

    strings:
        $h1={58 A4 53 E5} // VirtualAllocEx
        $h2={4C 77 26 07} // LoadLibraryEx
        $h3={6A C9 9C C9} // DNSQuery_UTF8
        $h4={44 F0 35 E0} // Sleep
        $h5={F4 00 8E CC} // lstrlen
    condition:
        2 of ( $h* )
}
