name: Sign Executable

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9
  PFX_PASSWORD: ${{ secrets.PFX_PASSWORD }}

jobs:
  sign-executable:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Compile with PyInstaller
      run: |
        pyinstaller mecau.py

    - name: Create self-signed certificate
      run: |
        openssl req -new -newkey rsa:4096 -x509 -sha256 -days 365 -nodes -out certified.pem -keyout certified.key
        openssl pkcs12 -export -out certified.pfx -inkey certified.key -in certified.pem -password pass:${{ env.PFX_PASSWORD }}

   
    - name: Sign Executable
      run: |
        signtool sign /f certified.pfx /p ${{ env.PFX_PASSWORD }} dist\mecau.exe
