name: Convert .py to .exe

on:
  push:
    branches:
      - main

env:
  PYTHON_VERSION: 3.9

jobs:
  sign-executable:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ env.PYTHON_VERSION }}

    - name: Install dependencies
      run: |
        pip install pyinstaller

    - name: Compile with PyInstaller
      run: |
        pyinstaller mecau.py
